apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-view
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","pods/log"]
  verbs: ["get", "list", "watch"]

