apiVersion: v1
kind: Pod
metadata:
  name: busybox-nginx-init
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: install
    image: busybox:1.31
    imagePullPolicy: IfNotPresent
    command: 
    - sh
    - -c
    - echo "Hello From Nginx" > /work-dir/index.html
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}


