#For role test
---
- hosts: all
  vars_prompt: 
    - name: k8s_internal_registry_username
      prompt: "Input Your Harbor's username"
      private: no
    - name: k8s_internal_registry_password
      prompt: "Input Your Harbor's password"
   
  gather_facts: no
  roles: 
    - role: kubernetes-common
    - role: kubernetes-extra