apiVersion: v1
kind: Pod
metadata:
  name: busybox-exceed
spec:
  containers:
  - image: busybox:1.31
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources: 
      requests:
          cpu: 2
  restartPolicy: Always
