apiVersion: v1
kind: Pod
metadata:
  name: busybox-v2
spec:
  containers:
  - image: busybox:1.31
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      limits:
        cpu: 200m
        memory: 256Mi 
      requests:
        cpu: 200m
        memory: 256Mi
  restartPolicy: Always
