---
# defaults file for ubuntu-common
external: true  # true for external,otherwise false
external_apt_source_file: "external_source.list"
internal_apt_source_file: "internal_source.list"
docker_gpg_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
packages_docker_deps:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent # This package is in xenial-update,xenial-security
  - software-properties-common
  - ipvsadm # This is for using IPVS proxier
  - aptitude
packages_docker: 
  - docker-ce
  - docker-ce-cli
  - containerd.io
external_docker_registry_mirrors: https://q1u34koz.mirror.aliyuncs.com # Full URL
internal_docker_registry_mirrors: 10.163.213.25:89 #ip:port
internal_docker_registry_https: lslab.ericsson.cn
python_interpreter_version: 3 # Python Version for node to be managed
python3_version: python3=3.5.1-3
install_file_path: installed_files #Path to store files on target 
external_dnsserver: "223.5.5.5"