apiVersion: v1
kind: Pod
metadata:
  name: group-y-antiaff2
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "web"
        topologyKey: nodeName
  containers:
  - name: cont2 
    image: gcr.io/google-samples/node-hello:1.0
    ports:
      - containerPort: 8080

