apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-view
  namespace: user1
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

