apiVersion: v1
kind: Pod
metadata:
  name: busybox-2containers
  namespace: default
spec:
  containers:
  - image: busybox:1.31
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-1
  - image: busybox:1.31
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-2
  restartPolicy: Always



