apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1g
  labels: 
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-storage
  local:
    path: /host_path_storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu-k8s-new-worker-1
          - ubuntu-k8s-new-worker-2
