#Install dependecies for Docker Swarm cluster
---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Update Ubuntu's hosts file
      copy:
        src: ceph-hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes 
            
    - name: Update Ubuntu's Apt repo file with updated server infomation 
      copy:
        src: sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: Update Ubuntu's DNS file
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: Disable APT dialy update service
      systemd:
        name: apt-daily.service
        state: stopped

 
    - name: Update APT with latest information
      apt:
        update_cache: yes

    - name: Install NTP Service
      apt:
        name: ntp
    - name: Copy upated NTP config file
      copy:
        src: ntp.conf
        dest: /etc/ntp.conf
    - name: Restart NTP Service
      systemd:
        name: ntp.service
        state: restarted                   
            
    - name: Change Time zone to CST
      file:
        src: /usr/share/zoneinfo/Asia/Shanghai
        dest: /etc/localtime

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes              
  