#Install dependecies for Docker Swarm cluster
---
- hosts: all
  gather_facts: false
  become: yes
  vars:
    ceph_user: doceph
  tasks:
    - name: Update Ubuntu's hosts file
      copy:
        src: ceph-hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes 
            
    - name: Update Ubuntu's Apt repo file with updated server infomation 
      copy:
        src: sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: Update Ubuntu's DNS file
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: Disable APT dialy update service
      systemd:
        name: apt-daily.service
        state: stopped

 
    - name: Update APT with latest information
      apt:
        update_cache: yes

    - name: Install NTP Service
      apt:
        name: ntp

    - name: Install Python 2
      apt: 
        name: python2.7

    - name: Create a Python link 
      file:
        src: "/usr/bin/python2.7"
        dest: "/usr/bin/python2"
        state: link    
               
    - name: Copy upated NTP config file
      copy:
        src: ntp.conf
        dest: /etc/ntp.conf
    - name: Restart NTP Service
      systemd:
        name: ntp.service
        state: restarted                   
            
    - name: Change Time zone to CST
      file:
        src: /usr/share/zoneinfo/Asia/Shanghai
        dest: /etc/localtime

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    - name: Add new user for Ceph
      user: 
        name: "{{ ceph_user }}"

    - name: Copy SSH privated key to new user's home    
      copy:
        src: ssh-key-private
        dest: /home/{{ ceph_user }}/.ssh/id_rsa

    - name: Set SSH key
      authorized_key:
        user: "{{ ceph_user }}"
        state: present
        key: '{{ item }}'
        #validate_certs: False
      with_file:
        - ssh-key-private.pub  

    - name: Add new user to sudo list
      lineinfile: 
        path: /etc/sudoers
        state: present
        line: '{{ item }}'    
        validate: 'visudo -cf %s'
      with_items: 
        - "{{ ceph_user }} ALL= (root) NOPASSWD:ALL"
                 
  