#Install dependecies for Docker Swarm cluster
---
- hosts: docker-swarm
  tasks:
    - name: install pip
      apt:
        name: python-pip
        state: present
    - name: upgrade pip
      shell: pip install --upgrade pip
    - name: copy pip command to /usr/bin
      shell: cp ~/.local/bin/pip /usr/bin
    - name: pip install docker-py
      pip: 
        name: docker-py


