apiVersion: v1
kind: Pod
metadata:
  name: busybox-top
  namespace: default
spec:
  containers:
  - image: busybox:1.31
    command:
      - top
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
