apiVersion: v1
kind: Pod
metadata:
  name: busybox-env
  namespace: default
spec:
  containers:
  - image: busybox:1.31
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    env: 
    - name: ENV1
      value: "Hello"
  restartPolicy: Always
