apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-pods
  #namespace: default
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: ericsson
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-view
  apiGroup: rbac.authorization.k8s.io

