apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
  #storageClassName: local-storage

