#Configuration for Kubernetes dependencies in K8s Clusters
---
- hosts: all
  gather_facts: false
  tasks:    
    # - name: Setup pip to local mirror
    #   shell: pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - name: Copy pip's docker packages to nodes
    # Offline packages are not included in this repo
      copy:
        src: pip-docker-packages # This name maybe different
        dest: /home/ubuntu/

    # - name: pip install docker
    #   #become: ubuntu
    #   pip: 
    #     name: docker
    #     extra_args: --user #-i https://pypi.tuna.tsinghua.edu.cn/simple
    
    - name: pip install docker offline packages
      #become: ubuntu
      pip: 
        requirements: /home/ubuntu/pip-docker-packages/requirements.txt
        extra_args: "--user --no-index --find-links=file:///home/ubuntu/pip-docker-packages"

    - name: Copy Google's APT key
      copy:
        src: apt-key-google.gpg
        dest: /home/ubuntu/apt-key-google.gpg
    - name: Add Google's official GPG key
      become: yes
      apt_key:
        id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
        file: /home/ubuntu/apt-key-google.gpg
    - name: Add k8s APT source link
      become: yes
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial main
    - name: Install kubernetes tools
      become: yes
      apt: 
        name: "{{ packages }}"
        update_cache: yes
      vars: 
        packages:
        - kubelet=1.16.2-00
        - kubeadm=1.16.2-00
        - kubectl=1.16.2-00


    # - name: Remove kubernetes tools
    #   apt: 
    #     name: "{{ packages }}"
    #     #update_cache: yes
    #     state: absent
    #   vars: 
    #     packages:
    #     - kubelet
    #     - kubeadm
    #     - kubectl

    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/coredns:1.6.2"
        repository: "k8s.gcr.io/coredns:1.6.2"


    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/etcd:3.3.15"
        repository: "k8s.gcr.io/etcd:3.3.15" 
        


    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/pause:3.1"
        repository: "k8s.gcr.io/pause:3.1"



    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-proxy:v1.16.2"
        repository: "k8s.gcr.io/kube-proxy:v1.16.2"   
        


    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-scheduler:v1.16.2"
        repository: "k8s.gcr.io/kube-scheduler:v1.16.2" 


    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-controller-manager:v1.16.2"
        repository: "k8s.gcr.io/kube-controller-manager:v1.16.2" 
        
        


    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-apiserver:v1.16.2"
        repository: "k8s.gcr.io/kube-apiserver:v1.16.2" 

    - name: Create a directory for hostPath Volume
      become: yes
      file:
        path: /host_path_storage
        state: directory
        mode: '0755'        

    - name: Create a directory for local PV
      become: yes
      file:
        path: /pv_local
        state: directory
        mode: '0755'          
        
        
        

        

       