#Configuration for Kubernetes dependencies in K8s Clusters
---
- hosts: all
  tasks:    
    # - name: Setup pip to local mirror
    #   shell: pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - name: Copy pip's docker packages to nodes
    # Offline packages are not included in this repo
      copy:
        src: pip-docker-packages # This name maybe different
        dest: /home/ubuntu/

    - name: pip install docker offline packages
      #become: ubuntu
      pip: 
        requirements: /home/ubuntu/pip-docker-packages/requirements.txt
        extra_args: "--user --no-index --find-links=file:///home/ubuntu/pip-docker-packages"
    - name: Copy Google's APT key
      copy:
        src: apt-key-google.gpg
        dest: /home/ubuntu/apt-key-google.gpg
    - name: Add Google's official GPG key
      become: yes
      apt_key:
        id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
        file: /home/ubuntu/apt-key-google.gpg
    - name: Add k8s APT source link
      become: yes
      lineinfile:
        path: /etc/apt/sources.list
        line: deb http://10.163.213.25:88/kubernetes kubernetes-xenial main
    - name: Install kubernetes tools
      become: yes
      apt: 
        name: "{{ packages }}"
        update_cache: yes
      vars: 
        packages:
        - kubelet=1.14.5-00
        - kubeadm=1.14.5-00
        - kubectl=1.14.5-00
    - name: Install NFS client
      become: yes
      apt:
        name: nfs-common

    # - name: Remove kubernetes tools
    #   apt: 
    #     name: "{{ packages }}"
    #     #update_cache: yes
    #     state: absent
    #   vars: 
    #     packages:
    #     - kubelet
    #     - kubeadm
    #     - kubectl
    - name: Pull k8s docker images
      docker_image:
        name: "10.163.213.25:89/library/coredns:1.3.1"
        repository: "k8s.gcr.io/coredns:1.3.1"


    - name: Pull k8s docker images
      docker_image:
        name: "10.163.213.25:89/library/etcd:3.3.10"
        repository: "k8s.gcr.io/etcd:3.3.10" 
        
        
    - name: Pull k8s docker images
      docker_image:
        name: "10.163.213.25:89/library/pause:3.1"
        repository: "k8s.gcr.io/pause:3.1"
        

    - name: Pull k8s docker images
      docker_image:
        name: "10.163.213.25:89/library/kube-proxy:v1.14.5"
        repository: "k8s.gcr.io/kube-proxy:v1.14.5"

         
        
        
    - name: Pull k8s docker images
      docker_image:
        name: "10.163.213.25:89/library/kube-scheduler:v1.14.5"
        repository: "k8s.gcr.io/kube-scheduler:v1.14.5" 
 
        
        
    - name: Pull k8s docker images
      docker_image:
        name: "10.163.213.25:89/library/kube-controller-manager:v1.14.5"
        repository: "k8s.gcr.io/kube-controller-manager:v1.14.5"
            
        
        
    - name: Pull k8s docker images
      docker_image:
        name: "10.163.213.25:89/library/kube-apiserver:v1.14.5"
        repository: "k8s.gcr.io/kube-apiserver:v1.14.5" 
    # - name: Chage image's tag
    #   docker_image:
    #     name: "10.163.213.25:89/library/kube-apiserver:v1.14.5"
    #    repository: "k8s.gcr.io/kube-apiserver:v1.14.5"
    - name: Create a directory for hostPath Volume
      become: yes
      file:
        path: /host_path_storage
        state: directory
        mode: '0755'        

    - name: Create a directory for local PV
      become: yes
      file:
        path: /pv_local
        state: directory
        mode: '0755'          
        
        
        

        

       