#Pull files and images for labs
---
- hosts: all
  #become: yes
  vars_prompt: 
    - name: harbor_admin_password
      prompt: "Input Harbor's password"

  tasks: 
    - name: Log into local registry
      docker_login:
        registry: 10.163.213.25:89
        username: admin
        password: '{{ harbor_admin_password }}'
    - name: Copy Weave's YAML file
      copy:
        src: weave-1.14.5.yml
        dest: /home/ubuntu/
    - name: Pull Weave CNI docker images
      docker_image:
        name: "10.163.213.25:89/library/weaveworks/weave-kube:2.5.2"
        repository: "weaveworks/weave-kube:2.5.2"
    # - name: Chanage Weave CNI image's tag
    #   docker_image:
    #     name: "10.163.213.25:89/library/weaveworks/weave-kube:2.5.2"
    #     repository: "weaveworks/weave-kube:2.5.2"

    
    - name: Pull Weave CNI docker images
      docker_image:
        name: "10.163.213.25:89/library/weaveworks/weave-npc:2.5.2"
        repository: "weaveworks/weave-npc:2.5.2"        
    # - name: Chanage Weave CNI image's tag
    #   docker_image:
    #     name: "10.163.213.25:89/library/weaveworks/weave-npc:2.5.2"
    #     repository: "weaveworks/weave-npc:2.5.2"        

    - name: Copy Flannel's YAML file
      copy:
        src: flannel-1.14.5.yml
        dest: /home/ubuntu/
    - name: Pull Flannel CNI docker images
      docker_image:
        name: "10.163.213.25:89/library/quay.io/coreos/flannel:v0.11.0-amd64"
        repository: "quay.io/coreos/flannel:v0.11.0-amd64"
        
    # - name: Chanage Flannel CNI image's tag
    #   docker_image:
    #     name: "10.163.213.25:89/library/quay.io/coreos/flannel:v0.11.0-amd64"
    #     repository: "quay.io/coreos/flannel:v0.11.0-amd64"         

    # - name: Copy Calico's YAML file
    #   copy:
    #     src: calico-1.14.5.yml
    #     dest: /home/ubuntu/
    # - name: Pull Calico CNI docker images
    #   docker_image:
    #     name: "10.163.213.25:89/library/calico/cni:v1.5.6"
    #     repository: "calico/cni:v1.5.6"
    # - name: Pull Calico CNI docker images
    #   docker_image:
    #     name: "10.163.213.25:89/library/calico/ctl:v1.0.2"
    #     repository: "calico/ctl:v1.5.6"
    # - name: Pull Calico CNI docker images
    #   docker_image:
    #     name: "10.163.213.25:89/library/calico/kube-policy-controller:v0.5.2"
    #     repository: "calico/kube-policy-controller:v0.5.2"   
    # - name: Pull Calico CNI docker images
    #   docker_image:
    #     name: "10.163.213.25:89/library/quay.io/calico/node:v1.0.2"
    #     repository: "quay.io/calico/node:v1.0.2"
    # - name: Pull Calico CNI docker images
    #   docker_image:
    #     name: "10.163.213.25:89/library/gcr.io/google_containers/etcd:2.2.1"
    #     repository: "gcr.io/google_containers/etcd:2.2.1" 
    - name: Copy Kubernetes Dashboard's YAML file
      copy:
        src: kubernetes-dashboard.yaml
        dest: /home/ubuntu/
    - name: Pull Kubernetes Dashboard docker images
      docker_image:
        name: "10.163.213.25:89/library/google_container/kubernetes-dashboard-amd64:v1.10.1"
        repository: "k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1"    
    - name: Pull Nginx 1.7.9 image
      docker_image:
        name: "10.163.213.25:89/library/nginx:1.7.9"
        repository: "nginx:1.7.9" 
    - name: Pull Nginx 1.9.1 image
      docker_image:
        name: "10.163.213.25:89/library/nginx:1.9.1"
        repository: "nginx:1.9.1"   
    - name: Copy Kubernetes Metrics Server's YAML files
      copy:
        src: metric-server
        dest: /home/ubuntu/
    - name: Pull Metric Server image
      docker_image:
        name: "10.163.213.25:89/library/google_container/metrics-server-amd64:v0.3.3"
        repository: "k8s.gcr.io/metrics-server-amd64:v0.3.3" 

    - name: Copy Kubernetes Nginx Ingress's YAML files
      copy:
        src: ingress-nginx
        dest: /home/ubuntu/

    - name: Pull Kubernetes Nginx Ingress image
      docker_image:
        name: "10.163.213.25:89/library/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1"
        repository: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1"         
                     
                                        
                        


                        


    