apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: groupYlabel
  name: groupy-service
spec:
  replicas: 2 
  selector:
    matchLabels:
      app.kubernetes.io/name: groupYlabel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: groupYlabel
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: groupy-service
        ports:
        - containerPort: 9999
