---
# defaults file for kubernetes-common
google_aptkey_file: apt-key-google.gpg
user_home: $HOME
yaml_file_path: yamls #Path to store files for lab use case
install_file_path: installed_files #Path to store files on target
app_file_path: app_files #Path to store files of 3pp, flannel,etc.
external: true  # true for extenal,otherwise false
pip_docker_packages_path: pip-docker-packages # path for files to offline install pip's docker module
k8s_apt_repo_external: deb https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial main
k8s_apt_repo_internal: deb http://10.163.213.25:88/kubernetes kubernetes-xenial main
#k8s_version: v1.20.10
k8s_packages:
  - kubelet=1.20.10-00               
  - kubeadm=1.20.10-00
  - kubectl=1.20.10-00
  - ipset 
k8s_external_registry: registry.cn-beijing.aliyuncs.com/thedada99/k8s-mirror/k8s.gcr.io
k8s_internal_registry: lslab.ericsson.cn
k8s_internal_registry_project: library
k8s_internal_registry_username: lslab
k8s_dashboard_file: kubernetes-dashboard.yml
k8s_flannel_file: kube-flannel-v0.13.0-amd64.yml
k8s_calico_crd_file: calico-custom-resources.yaml
k8s_calico_operator_file: calico-tigera-operator.yaml