apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: nons
spec:
  containers:
  - image: busybox:1.31
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
