apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "busybox-deployment-vol-v3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "busybox-vol"
  template:
    metadata:
      labels:
        app: "busybox-vol"
    spec:
      containers:
      - name: "busybox-vol-1"
        image: "busybox:1.31"
        command: ["/bin/sh","-c","env&sleep 3600"]
        volumeMounts: 
        - mountPath: /share-vol-1
          name: share-vol
      - name: "busybox-vol-2"
        image: "busybox:1.31"
        command: ["/bin/sh","-c","env&sleep 3600"]
        volumeMounts:
        - mountPath: /share-vol-2
          name: share-vol
      volumes: 
      - name: share-vol
        hostPath: 
          path: /host_path_storage_1 
          type: Directory


