apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-10
  namespace: default
spec:
  containers:
  - image: busybox:1.31
    command:
      - sleep
      - "10"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Never
