#Configuration for Docker in K8s Clusters
---
- hosts: k8s
  tasks:
    - name: copy Docer's daemon file to nodes for using local registry
      become: yes
      copy: 
        src: ../files/docker-daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
        backup: yes
    - name: Restart Docker Service
      become: yes 
      service:
        name: docker
        state: restarted
    - name: install pip
      become: yes
      apt:
        name: python-pip
        state: present
    # - name: upgrade pip to 19.03
    #   shell: pip install --upgrade pip
    # - name: copy pip command to /usr/bin
    #   become: yes
    #   shell: cp ~/.local/bin/pip /usr/bin
    - name: pip install docker-py
      become: yes
      pip: 
        name: docker-py


