#Pull files and images for labs
---
- hosts: all
  #become: yes
  tasks:  
    - name: Copy Weave's YAML file
      copy:
        src: weave-1.14.5.yml
        dest: /home/ubuntu/
    - name: Pull Weave CNI docker images
      docker_image:
        name: "weaveworks/weave-kube:2.5.2"
        #repository: "weaveworks/weave-kube:2.5.2"
    # - name: Chanage Weave CNI image's tag
    #   docker_image:
    #     name: "weaveworks/weave-kube:2.5.2"
    #     #repository: "weaveworks/weave-kube:2.5.2"

    
    - name: Pull Weave CNI docker images
      docker_image:
        name: "weaveworks/weave-npc:2.5.2"
        #repository: "weaveworks/weave-npc:2.5.2"        
    # - name: Chanage Weave CNI image's tag
    #   docker_image:
    #     name: "weaveworks/weave-npc:2.5.2"
    #     #repository: "weaveworks/weave-npc:2.5.2"        

    - name: Copy Flannel's YAML file
      copy:
        src: flannel-1.14.5.yml
        dest: /home/ubuntu/
    - name: Pull Flannel CNI docker images
      docker_image:
        name: "quay.io/coreos/flannel:v0.11.0-amd64"
        #repository: "quay.io/coreos/flannel:v0.11.0-amd64"
    # - name: Chanage Flannel CNI image's tag
    #   docker_image:
    #     name: "quay.io/coreos/flannel:v0.11.0-amd64"
    #     #repository: "quay.io/coreos/flannel:v0.11.0-amd64"         

    - name: Copy Calico's YAML file
      copy:
        src: calico-v3.9.yml
        dest: /home/ubuntu/
    - name: Pull Calico CNI docker images
      docker_image:
        name: "calico/cni:v3.9.0"
        #repository: "calico/cni:v1.5.6"
    # - name: Pull Calico CNI docker images
    #   docker_image:
    #     name: "calico/ctl:v1.0.2"
    #     #repository: "calico/ctl:v1.5.6"
    - name: Pull Calico CNI docker images
      docker_image:
        name: "calico/pod2daemon-flexvol:v3.9.0"
        #repository: "calico/kube-policy-controller:v0.5.2"   
    - name: Pull Calico CNI docker images
      docker_image:
        name: "calico/node:v3.9.0"
        #repository: "quay.io/calico/node:v1.0.2"
    - name: Pull Calico CNI docker images
      docker_image:
        name: "calico/kube-controllers:v3.9.0"
        #repository: "gcr.io/google_containers/etcd:2.2.1" 

        
    - name: Pull Nginx 1.7.9 image
      docker_image:
        name: "nginx:1.7.9"
        #repository: "nginx:1.7.9" 
    - name: Pull Nginx 1.9.1 image
      docker_image:
        name: "nginx:1.9.1"
        #repository: "nginx:1.9.1"         
                                        
                        


                        


    