#Configuration for Kubernetes dependencies in K8s Clusters
---
- hosts: all
  tasks:    
    # - name: Setup pip to local mirror
    #   shell: pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          
    - name: pip install docker
      pip: 
        name: docker
    - name: Copy Google's APT key
      copy:
        src: apt-key-google.gpg
        dest: /home/ubuntu/apt-key-google.gpg
    - name: Add Google's official GPG key
      become: yes
      apt_key:
        id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
        file: /home/ubuntu/apt-key-google.gpg
    - name: Add k8s APT source link
      become: yes
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://mirrors.ustc.edu.cn/kubernetes/apt/ kubernetes-xenial main
    - name: Instal kubernetes tools
      become: yes
      apt: 
        name: "{{ packages }}"
        update_cache: yes
      vars: 
        packages:
        - kubelet=1.14.5-00
        - kubeadm=1.14.5-00
        - kubectl=1.14.5-00        
    # - name: Remove kubernetes tools
    #   apt: 
    #     name: "{{ packages }}"
    #     #update_cache: yes
    #     state: absent
    #   vars: 
    #     packages:
    #     - kubelet
    #     - kubeadm
    #     - kubectl
    - name: Pull k8s docker images
      docker_image:
        name: "gcr.azk8s.cn/google_containers/coredns:1.3.1"

    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/coredns:1.3.1"
        repository: "k8s.gcr.io/coredns:1.3.1"

    - name: Pull k8s docker images
      docker_image:
        name: "gcr.azk8s.cn/google_containers/etcd:3.3.10"

    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/etcd:3.3.10"
        repository: "k8s.gcr.io/etcd:3.3.10" 
        
    - name: Pull k8s docker images
      docker_image:
        name: "gcr.azk8s.cn/google_containers/pause:3.1"

    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/pause:3.1"
        repository: "k8s.gcr.io/pause:3.1"

    - name: Pull k8s docker images
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-proxy:v1.14.5"

    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-proxy:v1.14.5"
        repository: "k8s.gcr.io/kube-proxy:v1.14.5"   
        
        
    - name: Pull k8s docker images
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-scheduler:v1.14.5"

    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-scheduler:v1.14.5"
        repository: "k8s.gcr.io/kube-scheduler:v1.14.5" 
        
    - name: Pull k8s docker images
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-controller-manager:v1.14.5"

    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-controller-manager:v1.14.5"
        repository: "k8s.gcr.io/kube-controller-manager:v1.14.5" 
        
        
    - name: Pull k8s docker images
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-apiserver:v1.14.5"

    - name: Chage image's tag
      docker_image:
        name: "gcr.azk8s.cn/google_containers/kube-apiserver:v1.14.5"
        repository: "k8s.gcr.io/kube-apiserver:v1.14.5" 
        
        
        

        

       