#Install dependecies for Docker Swarm cluster
---
- hosts: all
  become: yes
  tasks:
    - name: Update Ubuntu's Apt repo file with updated server infomation 
      copy:
        src: sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644
        backup: yes
    - name: Update Ubuntu's hosts file
      copy:
        src: k8s-new-hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes 
    - name: Update Ubuntu's DNS file
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
        backup: yes                
        
    - name: Copy Docker's offical GPG key
      copy:
        src: docker.gpg
        dest: /home/ubuntu/docker.gpg
    - name: Add Docker's official GPG key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        file: /home/ubuntu/docker.gpg        
    - name: Update Apt with latest information
      apt: 
        name: "{{ packages }}"
        update_cache: yes
      vars: 
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Install Docker CE
      apt:
        name: "{{ packages_docker }}" 
        update_cache: yes
      vars:
        packages_docker:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: copy Docer's daemon file to nodes for using local registry
      copy: 
        src: docker-daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
        backup: yes 
    - name: Add user "ubuntu" to group "docker"
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Restart Docker Service
      become: yes 
      service:
        name: docker
        state: restarted
    - name: Change Time zone to CST
      file:
        src: /usr/share/zoneinfo/Asia/Shanghai
        dest: /etc/localtime
    - name: Remove Python2
      apt:
        name: python
        state: absent
    - name: Remove Python2's pip
      apt:
        name: python-pip
        state: absent        
    - name: Install Python 3.5.1
      apt:
        name: python3=3.5.1-3
        update_cache: yes

    - name: Install pip for Python 3
      apt:
        name: python3-pip=8.1.1-2
        update_cache: yes        
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes        




        
  