#Configuration for Docker in K8s Clusters
---
- hosts: k8s
  become: yes
  tasks:    
    - name: pull an image
      docker_image:
        name: 10.163.213.25:5000/calico/cni:v3.5.2
    - name: tag previous image
      docker_image:
        name: 10.163.213.25:5000/calico/cni:v3.5.2
        repository: calico/cni:v3.5.2      
    - name: pull an image
      docker_image:
        name: 10.163.213.25:5000/calico/node:v3.5.2
    - name: tag previous image
      docker_image:
        name: 10.163.213.25:5000/calico/node:v3.5.2
        repository: calico/node:v3.5.2     
    - name: pull an image
      docker_image:
        name: 10.163.213.25:5000/fluent/fluent-bit:latest
    - name: tag previous image
      docker_image:
        name: 10.163.213.25:5000/fluent/fluent-bit:latest
        repository: fluent/fluent-bit:latest             
    - name: pull an image and change the tag to original one
      docker_image:
        name: 10.163.213.25:5000/k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
        repository: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1   
    - name: remove tag of local registry
      docker_image:
        state: absent
        name: 10.163.213.25:5000/k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
        tag: v1.10.1
   #  - name: tag previous image
   #    docker_image:
   #      name: 10.163.213.25:5000/k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
   #      repository: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1             
   # 