apiVersion: v1
kind: Pod
metadata:
  name: busybox-2containers-with-vol
  namespace: default
spec:
  containers:
  - image: busybox:1.31
    command:
      - sh
      - -c
      - touch /busy-1/newfile&sleep 3600
    volumeMounts:
    - name: data
      mountPath: /busy-1
    imagePullPolicy: IfNotPresent
    name: busybox-1
  - image: busybox:1.31
    command:
      - sh
      - -c
      - touch /busy-2/newfile&sleep 3600
    volumeMounts:
    - name: data
      mountPath: /busy-2
    imagePullPolicy: IfNotPresent
    name: busybox-2
  restartPolicy: Always
  volumes:
  - name: data
    emptyDir: {}



